version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend/api1
    container_name: backend
    command: npm start
    volumes:
      - ./backend/api1:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/cinebook
    container_name: frontend
    command: npm start
    volumes:
      - ./frontend/cinebook:/app
      - /app/node_modules
    ports:
      - '4200:4200'
    depends_on:
      - backend

volumes:
  mongo_data: