services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - '27017:27017'
    networks:
      - globsyn-network
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend/api1
    container_name: backend
    command: npm start
    volumes:
      - ./backend/api1:/app
    ports:
      - '5000:5000'
    networks:
      - globsyn-network
    depends_on:
      - mongo

  # frontend:
  #   build:
  #     context: ./frontend/cinebook
  #   container_name: frontend
  #   command: npm start
  #   volumes:
  #     - ./frontend/cinebook:/app
  #   ports:
  #     - '4200:4200'
  #   networks:
  #     - globsyn-network

volumes:
  mongo_data:

networks:
  globsyn-network:
    driver: bridge